# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0002_auto_20171108_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('follow', 'follower')]),
        ),
    ]
